--- #YAML:1.0
name:                Devel-Pillbug
version:             0.004
abstract:            ~
license:             perl
author:              
    - Alex Ayars <pause@nodekit.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::HomeDir:                 0.86
    File::Type:                    0.22
    HTTP::Server::Simple::Mason:   0.13
    Net::Server:                   0.97
    Test::More:                    0.86
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
